# Pandas Series'e Giriş

In [1]:
import numpy as np
import pandas as pd

In [2]:
grade = { "Ali" : 100, "Melih" : 90, "Feza" : 70 }

In [3]:
pd.Series(grade)

Ali      100
Melih     90
Feza      70
dtype: int64

In [7]:
names = ["Ali", "Melih", "Feza"]
grades = [100, 90, 70]

In [8]:
pd.Series(names)

0      Ali
1    Melih
2     Feza
dtype: object

In [9]:
pd.Series(grades)

0    100
1     90
2     70
dtype: int64

In [11]:
pd.Series(data = grades, index = names)

Ali      100
Melih     90
Feza      70
dtype: int64

## Numpy ile Pandas Serileri

In [12]:
numpy_array = np.array([50,40,30,20])

In [13]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int32

## Pandas Serieslerde Aritmetik İşlemler

In [14]:
result_1 = pd.Series(data= [100, 90, 70], index=["Ali", "Melih", "Feza"])
result_2 = pd.Series(data= [80, 80, 70], index=["Ali", "Melih", "Feza"])

In [15]:
result_1["Ali"]

100

In [16]:
result_2["Melih"]

80

In [17]:
result_1 + result_2

Ali      180
Melih    170
Feza     140
dtype: int64

In [18]:
result_1 * result_2

Ali      8000
Melih    7200
Feza     4900
dtype: int64

In [19]:
result_1 - result_2

Ali      20
Melih    10
Feza      0
dtype: int64

In [20]:
result_1 / result_2

Ali      1.250
Melih    1.125
Feza     1.000
dtype: float64

### İndexleri Farklı Olan Pandas Seriesleri Toplama

In [21]:
different_series_1 = pd.Series([20,30,40,50],["a","b","c","d"])
different_series_2 = pd.Series([20,10,40,70],["a","c","f","g"])

In [22]:
different_series_1 + different_series_2

a    40.0
b     NaN
c    50.0
d     NaN
f     NaN
g     NaN
dtype: float64

Series Dataframeden farklı olarak sadece 1 boyutludur. Yani bir tablonun sadece 1 kolonunu ifade eder.

# Pandas DataFrame

In [25]:
data = np.random.randn(4, 3)
data

array([[-1.03038097, -1.94502299,  1.99921024],
       [ 1.0466207 ,  0.29333657,  2.21922397],
       [ 0.47448843,  0.16657258, -0.65416387],
       [ 0.92557533,  1.72636947, -1.82782949]])

In [26]:
data_frame = pd.DataFrame(data = data)

In [27]:
data_frame

          0         1         2
0 -1.030381 -1.945023  1.999210
1  1.046621  0.293337  2.219224
2  0.474488  0.166573 -0.654164
3  0.925575  1.726369 -1.827829

In [28]:
type(data_frame)

pandas.core.frame.DataFrame

In [29]:
type(data_frame[0])

pandas.core.series.Series

In [30]:
new_df = pd.DataFrame(data=data, index=["Ali", "Feza", "Melih", "Ramo"], columns=["Yaş", "Maaş", "Boy"])

In [31]:
new_df

            Yaş      Maaş       Boy
Ali   -1.030381 -1.945023  1.999210
Feza   1.046621  0.293337  2.219224
Melih  0.474488  0.166573 -0.654164
Ramo   0.925575  1.726369 -1.827829

In [32]:
new_df["Yaş"]

Ali     -1.030381
Feza     1.046621
Melih    0.474488
Ramo     0.925575
Name: Yaş, dtype: float64

In [33]:
new_df[["Yaş", "Boy"]]

            Yaş       Boy
Ali   -1.030381  1.999210
Feza   1.046621  2.219224
Melih  0.474488 -0.654164
Ramo   0.925575 -1.827829

In [34]:
new_df.loc["Ali"]

Yaş    -1.030381
Maaş   -1.945023
Boy     1.999210
Name: Ali, dtype: float64

In [35]:
new_df.iloc[0]

Yaş    -1.030381
Maaş   -1.945023
Boy     1.999210
Name: Ali, dtype: float64