# Pandas Series'e Giriş

In [1]:
import numpy as np
import pandas as pd

In [2]:
grade = { "Ali" : 100, "Melih" : 90, "Feza" : 70 }

In [3]:
pd.Series(grade)

Ali      100
Melih     90
Feza      70
dtype: int64

In [4]:
names = ["Ali", "Melih", "Feza"]
grades = [100, 90, 70]

In [5]:
pd.Series(names)

0      Ali
1    Melih
2     Feza
dtype: object

In [6]:
pd.Series(grades)

0    100
1     90
2     70
dtype: int64

In [7]:
pd.Series(data = grades, index = names)

Ali      100
Melih     90
Feza      70
dtype: int64

## Numpy ile Pandas Serileri

In [8]:
numpy_array = np.array([50,40,30,20])

In [9]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int32

## Pandas Serieslerde Aritmetik İşlemler

In [10]:
result_1 = pd.Series(data= [100, 90, 70], index=["Ali", "Melih", "Feza"])
result_2 = pd.Series(data= [80, 80, 70], index=["Ali", "Melih", "Feza"])

In [11]:
result_1["Ali"]

100

In [12]:
result_2["Melih"]

80

In [13]:
result_1 + result_2

Ali      180
Melih    170
Feza     140
dtype: int64

In [14]:
result_1 * result_2

Ali      8000
Melih    7200
Feza     4900
dtype: int64

In [15]:
result_1 - result_2

Ali      20
Melih    10
Feza      0
dtype: int64

In [16]:
result_1 / result_2

Ali      1.250
Melih    1.125
Feza     1.000
dtype: float64

### İndexleri Farklı Olan Pandas Seriesleri Toplama

In [17]:
different_series_1 = pd.Series([20,30,40,50],["a","b","c","d"])
different_series_2 = pd.Series([20,10,40,70],["a","c","f","g"])

In [18]:
different_series_1 + different_series_2

a    40.0
b     NaN
c    50.0
d     NaN
f     NaN
g     NaN
dtype: float64

Series Dataframeden farklı olarak sadece 1 boyutludur. Yani bir tablonun sadece 1 kolonunu ifade eder.

# Pandas DataFrame

In [19]:
data = np.random.randn(4, 3)
data

array([[ 0.8907376 , -0.26348303,  0.61518784],
       [ 2.11553388, -0.24628805, -1.38946119],
       [ 1.56349313,  0.14241528, -0.14138222],
       [ 1.14185752,  0.84520608, -1.51977901]])

In [20]:
data_frame = pd.DataFrame(data = data)

In [21]:
data_frame

          0         1         2
0  0.890738 -0.263483  0.615188
1  2.115534 -0.246288 -1.389461
2  1.563493  0.142415 -0.141382
3  1.141858  0.845206 -1.519779

In [22]:
type(data_frame)

pandas.core.frame.DataFrame

In [23]:
type(data_frame[0])

pandas.core.series.Series

In [24]:
new_df = pd.DataFrame(data=data, index=["Ali", "Feza", "Melih", "Ramo"], columns=["Yaş", "Maaş", "Boy"])

In [25]:
new_df

            Yaş      Maaş       Boy
Ali    0.890738 -0.263483  0.615188
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382
Ramo   1.141858  0.845206 -1.519779

In [26]:
new_df["Yaş"]

Ali      0.890738
Feza     2.115534
Melih    1.563493
Ramo     1.141858
Name: Yaş, dtype: float64

In [27]:
new_df[["Yaş", "Boy"]]

            Yaş       Boy
Ali    0.890738  0.615188
Feza   2.115534 -1.389461
Melih  1.563493 -0.141382
Ramo   1.141858 -1.519779

In [28]:
new_df.loc["Ali"]

Yaş     0.890738
Maaş   -0.263483
Boy     0.615188
Name: Ali, dtype: float64

In [29]:
new_df.iloc[0]

Yaş     0.890738
Maaş   -0.263483
Boy     0.615188
Name: Ali, dtype: float64

## Data Manüpülasyon

In [30]:
new_df

            Yaş      Maaş       Boy
Ali    0.890738 -0.263483  0.615188
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382
Ramo   1.141858  0.845206 -1.519779

In [32]:
new_df["Extra"] = 10

In [33]:
new_df

            Yaş      Maaş       Boy  Extra
Ali    0.890738 -0.263483  0.615188     10
Feza   2.115534 -0.246288 -1.389461     10
Melih  1.563493  0.142415 -0.141382     10
Ramo   1.141858  0.845206 -1.519779     10

In [34]:
new_df.drop("Extra", axis = 1)

            Yaş      Maaş       Boy
Ali    0.890738 -0.263483  0.615188
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382
Ramo   1.141858  0.845206 -1.519779

In [35]:
new_df

            Yaş      Maaş       Boy  Extra
Ali    0.890738 -0.263483  0.615188     10
Feza   2.115534 -0.246288 -1.389461     10
Melih  1.563493  0.142415 -0.141382     10
Ramo   1.141858  0.845206 -1.519779     10

In [36]:
new_df.drop("Extra", axis = 1, inplace=True)

In [37]:
new_df

            Yaş      Maaş       Boy
Ali    0.890738 -0.263483  0.615188
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382
Ramo   1.141858  0.845206 -1.519779

In [39]:
new_df.drop("Ramo", axis = 0)

            Yaş      Maaş       Boy
Ali    0.890738 -0.263483  0.615188
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382

In [43]:
new_df.loc["Feza"]["Yaş"]

2.115533881232932

In [44]:
new_df.loc["Feza", "Yaş"]

2.115533881232932

In [45]:
boolean_dataframe = new_df > 0

In [46]:
boolean_dataframe

        Yaş   Maaş    Boy
Ali    True  False   True
Feza   True  False  False
Melih  True   True  False
Ramo   True   True  False

In [47]:
new_df[new_df > 0]

            Yaş      Maaş       Boy
Ali    0.890738       NaN  0.615188
Feza   2.115534       NaN       NaN
Melih  1.563493  0.142415       NaN
Ramo   1.141858  0.845206       NaN

In [49]:
new_df[new_df["Yaş"] > 1.5]

            Yaş      Maaş       Boy
Feza   2.115534 -0.246288 -1.389461
Melih  1.563493  0.142415 -0.141382

## DataFrame Index Mantığı

In [50]:
new_df.reset_index()

   index       Yaş      Maaş       Boy
0    Ali  0.890738 -0.263483  0.615188
1   Feza  2.115534 -0.246288 -1.389461
2  Melih  1.563493  0.142415 -0.141382
3   Ramo  1.141858  0.845206 -1.519779

Bu şekilde normalde olan indexleri dataframe içerisine alıp yana ise 0'dan başlayacak şekilde index ataması yapabiliriz.

In [51]:
new_indices = ["A", "F", "M", "R"]
new_df["New Index"] = new_indices

In [52]:
new_df

            Yaş      Maaş       Boy New Index
Ali    0.890738 -0.263483  0.615188         A
Feza   2.115534 -0.246288 -1.389461         F
Melih  1.563493  0.142415 -0.141382         M
Ramo   1.141858  0.845206 -1.519779         R

In [53]:
new_df.set_index("New Index", inplace=True)

In [54]:
new_df

                Yaş      Maaş       Boy
New Index
A          0.890738 -0.263483  0.615188
F          2.115534 -0.246288 -1.389461
M          1.563493  0.142415 -0.141382
R          1.141858  0.845206 -1.519779

In [58]:
new_df.loc["A"]

Yaş     0.890738
Maaş   -0.263483
Boy     0.615188
Name: A, dtype: float64

## MultiIndex

In [59]:
first_index = ["Doğu","Doğu","Batı","Batı","Batı"]
second_index = ["Ali", "Yakub", "Feza", "Melih", "Ramo"]

In [60]:
zipped_index = list(zip(first_index, second_index))

In [61]:
zipped_index

[('Doğu', 'Ali'),
 ('Doğu', 'Yakub'),
 ('Batı', 'Feza'),
 ('Batı', 'Melih'),
 ('Batı', 'Ramo')]

In [62]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [63]:
zipped_index

MultiIndex([('Doğu',   'Ali'),
            ('Doğu', 'Yakub'),
            ('Batı',  'Feza'),
            ('Batı', 'Melih'),
            ('Batı',  'Ramo')],
           )

In [68]:
sample_values = np.ones((5,2))

In [69]:
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
big_df = pd.DataFrame(
    data = sample_values,
    index= zipped_index,
    columns=["Age", "Salary"]
)

In [71]:
big_df

            Age  Salary
Doğu Ali    1.0     1.0
     Yakub  1.0     1.0
Batı Feza   1.0     1.0
     Melih  1.0     1.0
     Ramo   1.0     1.0

In [72]:
big_df["Age"]

Doğu  Ali      1.0
      Yakub    1.0
Batı  Feza     1.0
      Melih    1.0
      Ramo     1.0
Name: Age, dtype: float64

In [73]:
big_df.loc["Doğu"]

       Age  Salary
Ali    1.0     1.0
Yakub  1.0     1.0

In [75]:
big_df.loc["Doğu"].loc["Yakub"]

Age       1.0
Salary    1.0
Name: Yakub, dtype: float64