# Excel'den Veri Okumak

In [1]:
import numpy as np
import pandas as pd

In [2]:
weather_df = pd.read_excel("2-weather.xlsx")

In [3]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [4]:
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [5]:
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [6]:
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

## Boş Değerler İle Çalışmak

In [7]:
weather_na_df = pd.read_excel("3-weatherna.xlsx")

In [8]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [9]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [10]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [11]:
weather_na_df["Paris"].count()

6

In [12]:
weather_na_df["Amsterdam"].count()

8

In [13]:
weather_na_df["Paris"].isna()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
Name: Paris, dtype: bool

In [14]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [15]:
weather_na_df.dropna()

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [16]:
weather_na_df.dropna(axis = 0)

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [17]:
weather_na_df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
weather_na_df.drop(columns='Paris', axis=1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [19]:
weather_na_df.fillna("ali")

  Istanbul New York Amsterdam Paris
0     20.0     10.0      15.0  12.0
1     21.0     10.0       ali  14.0
2      ali     13.0      18.0  15.0
3     22.0     14.0      19.0  18.0
4     25.0     15.0      15.0  20.0
5     28.0      ali      22.0   ali
6     15.0     12.0      15.0  15.0
7     20.0     15.0      14.0   ali
8     22.0     16.0      16.0   ali

In [20]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [21]:
weather_na_df.fillna(weather_na_df.mean())

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [22]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [23]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64

## Employee Dataseti

In [24]:
df = pd.read_csv("3-employee.csv")

In [25]:
df

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York

In [26]:
df.describe()

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [27]:
df["Salary"].mean()

78344.5

In [28]:
df[["Salary", "Experience"]].mean()

Salary        78344.50
Experience        7.06
dtype: float64

In [29]:
df.count()

Department    50
Employee      50
Salary        50
Experience    50
City          50
dtype: int64

In [30]:
df.head()

  Department Employee  Salary  Experience           City
0  Marketing    Emp_1   53483           1       New York
1      Sales    Emp_2   78555           8         Austin
2    Finance    Emp_3   47159           3         Austin
3      Sales    Emp_4  110077           3  San Francisco
4      Sales    Emp_5   65920           1       New York

In [31]:
df.groupby('Department')

In [32]:
df_grouped_department = df.groupby('Department')

In [33]:
df_grouped_department.count()

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [34]:
df_grouped_department['Salary'].mean()

Department
Finance      90552.700000
HR           76182.571429
IT           63381.600000
Marketing    79555.000000
Sales        81038.900000
Name: Salary, dtype: float64

In [35]:
df_grouped_department.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

## Concat

In [36]:
df1 = pd.read_csv("3-concat_data1.csv")

In [37]:
df1

   Employee_ID    Name Department
0            1   Emp_1    Finance
1            2   Emp_2  Marketing
2            3   Emp_3         HR
3            4   Emp_4    Finance
4            5   Emp_5    Finance
5            6   Emp_6  Marketing
6            7   Emp_7         HR
7            8   Emp_8         HR
8            9   Emp_9    Finance
9           10  Emp_10         IT

In [38]:
df2 = pd.read_csv("3-concat_data2.csv")

In [39]:
df2

   Employee_ID    Name Department
0           11  Emp_11    Finance
1           12  Emp_12    Finance
2           13  Emp_13    Finance
3           14  Emp_14    Finance
4           15  Emp_15  Marketing
5           16  Emp_16         HR
6           17  Emp_17  Marketing
7           18  Emp_18  Marketing
8           19  Emp_19  Marketing
9           20  Emp_20    Finance

In [40]:
df_concat = pd.concat(
    objs = [df1, df2],
    ignore_index=True
)

In [41]:
df_concat

    Employee_ID    Name Department
0             1   Emp_1    Finance
1             2   Emp_2  Marketing
2             3   Emp_3         HR
3             4   Emp_4    Finance
4             5   Emp_5    Finance
5             6   Emp_6  Marketing
6             7   Emp_7         HR
7             8   Emp_8         HR
8             9   Emp_9    Finance
9            10  Emp_10         IT
10           11  Emp_11    Finance
11           12  Emp_12    Finance
12           13  Emp_13    Finance
13           14  Emp_14    Finance
14           15  Emp_15  Marketing
15           16  Emp_16         HR
16           17  Emp_17  Marketing
17           18  Emp_18  Marketing
18           19  Emp_19  Marketing
19           20  Emp_20    Finance

## Merge

In [42]:
df_merge1 = pd.read_csv("3-merge_data1.csv")

In [43]:
df_merge1

   Employee_ID    Name Department
0            1   Emp_1         IT
1            2   Emp_2         HR
2            3   Emp_3         IT
3            4   Emp_4  Marketing
4            5   Emp_5  Marketing
5            6   Emp_6         IT
6            7   Emp_7         IT
7            8   Emp_8         IT
8            9   Emp_9  Marketing
9           10  Emp_10  Marketing

In [44]:
df_merge2 = pd.read_csv("3-merge_data2.csv")

In [45]:
df_merge2

   Employee_ID  Salary  Experience
0            5   55658           3
1            1  114478           5
2           12   48431          19
3           10   32747           7
4            6   89150           9
5           13   95725           7
6            9   65773           4
7           11   86886          18

In [46]:
# merge - inner join
df_merged_inner = pd.merge(
    left = df_merge1,
    right= df_merge2,
    on = 'Employee_ID',    # Hangileri üzerinden eşleşme sağlayıp birleştireceğimizi seçiyor
    how = 'inner'
)

In [47]:
df_merged_inner

   Employee_ID    Name Department  Salary  Experience
0            1   Emp_1         IT  114478           5
1            5   Emp_5  Marketing   55658           3
2            6   Emp_6         IT   89150           9
3            9   Emp_9  Marketing   65773           4
4           10  Emp_10  Marketing   32747           7

In [48]:
# merge - outer join
df_merged_outer = pd.merge(
    left = df_merge1,
    right = df_merge2,
    on = 'Employee_ID',
    how = 'outer'
)

df_merged_outer

    Employee_ID    Name Department    Salary  Experience
0             1   Emp_1         IT  114478.0         5.0
1             2   Emp_2         HR       NaN         NaN
2             3   Emp_3         IT       NaN         NaN
3             4   Emp_4  Marketing       NaN         NaN
4             5   Emp_5  Marketing   55658.0         3.0
5             6   Emp_6         IT   89150.0         9.0
6             7   Emp_7         IT       NaN         NaN
7             8   Emp_8         IT       NaN         NaN
8             9   Emp_9  Marketing   65773.0         4.0
9            10  Emp_10  Marketing   32747.0         7.0
10           11     NaN        NaN   86886.0        18.0
11           12     NaN        NaN   48431.0        19.0
12           13     NaN        NaN   95725.0         7.0

In [50]:
# merge - left join
df_merged_left = pd.merge(
    left = df_merge1,
    right = df_merge2,
    on = 'Employee_ID',
    how = 'left'
)

df_merged_left

   Employee_ID    Name Department    Salary  Experience
0            1   Emp_1         IT  114478.0         5.0
1            2   Emp_2         HR       NaN         NaN
2            3   Emp_3         IT       NaN         NaN
3            4   Emp_4  Marketing       NaN         NaN
4            5   Emp_5  Marketing   55658.0         3.0
5            6   Emp_6         IT   89150.0         9.0
6            7   Emp_7         IT       NaN         NaN
7            8   Emp_8         IT       NaN         NaN
8            9   Emp_9  Marketing   65773.0         4.0
9           10  Emp_10  Marketing   32747.0         7.0

In [51]:
# merge - right join
df_merged_right = pd.merge(
    left = df_merge1,
    right = df_merge2,
    on = 'Employee_ID',
    how = 'right'
)

df_merged_right

   Employee_ID    Name Department  Salary  Experience
0            5   Emp_5  Marketing   55658           3
1            1   Emp_1         IT  114478           5
2           12     NaN        NaN   48431          19
3           10  Emp_10  Marketing   32747           7
4            6   Emp_6         IT   89150           9
5           13     NaN        NaN   95725           7
6            9   Emp_9  Marketing   65773           4
7           11     NaN        NaN   86886          18

## Apply

In [52]:
df = pd.read_csv("3-apply_function_data.csv")

In [53]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [54]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [56]:
# Örnek 1: Maaşlarına göre işçileri sınıflandıran bir fonksiyon 
def salary_category(salary):
    if salary < 50000:
        return 'Low'
    elif 5000 <= salary < 80000:
        return 'Medium'
    else:
        return 'High'

In [57]:
df['Salary_Category'] = df['Salary'].apply(salary_category)

In [58]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [59]:
# Örnek 2: Tecrübelerine göre işçilerin performans skorlarını 1 arttıran fonksiyon
def adjust_performance(df):
    if df['Experience'] > 10:
        df['Performance_Score'] += 1
    return df['Performance_Score']

In [60]:
df['Adjusted_Performance'] = df.apply(adjust_performance, axis = 1)

df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Performance
0,1,Emp_1,Marketing,82251,6,5,High,5
1,2,Emp_2,Sales,52662,24,3,Medium,4
2,3,Emp_3,Finance,38392,5,3,Low,3
3,4,Emp_4,Sales,60535,20,3,Medium,4
4,5,Emp_5,Sales,108603,2,2,High,2
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5
96,97,Emp_97,Sales,100467,22,2,High,3
97,98,Emp_98,IT,82662,23,3,High,4
98,99,Emp_99,IT,42688,22,1,Low,2
99,100,Emp_100,HR,55342,14,3,Medium,4

In [61]:
# Örnek 3: İsim kısmında _ yerlerine boşluk koyan bir uygulama

df['Formatted_Names'] = df['Name'].apply(lambda x: x.replace('_', ' '))

In [62]:
df.head()

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Performance,Formatted_Names
0,1,Emp_1,Marketing,82251,6,5,High,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,2,Emp 5